name: VoiceApp Data Hub

'on':
    - pull_request

concurrency:
    group: '${{ github.workflow }}-${{ github.head_ref || github.run_id }}'
    cancel-in-progress: true

jobs:
    test_setup:
        name: Setup tests
        runs-on: ubuntu-latest
        outputs:
            preview_url: '${{ steps.waitForVercelPreviewDeployment.outputs.url }}'
        steps:
            - name: Wait for Vercel preview deployment to be ready
              uses: patrickedqvist/wait-for-vercel-preview@main
              id: waitForVercelPreviewDeployment
              with:
                  check_interval: 5
                  max_timeout: 300
                  token: '${{ secrets.GITHUB_TOKEN }}'

    test_e2e:
        name: Run end-to-end tests
        needs: test_setup
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                containers:
                    - 1
                    - 2
                    - 3
                    - 4
                    - 5
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.0
              with:
                  access_token: '${{ github.token }}'

            - name: Cache Firebase Emulator Binaries
              uses: actions/cache@v2.1.6
              with:
                  path: ~/.cache/firebase/emulators
                  key: >-
                      ${{ runner.os }}-firebase-${{
                      steps.cache-settings.outputs.firebase-tools }}

            - uses: actions/checkout@v2

            - run: echo '${{ secrets.FIREBASE_RUNTIME_CONFIG }}' > ./functions/.runtimeconfig.json && echo '${{ secrets.SERVICE_ACCOUNT }}' > ./serviceAccount.json

            - name: Run Cypress
              uses: cypress-io/github-action@v2
              with:
                  build: 'yarn build:emulator --project ${{ secrets.FIREBASE_PROJECT_ID }}'
                  start: 'yarn start:emulator --project ${{ secrets.FIREBASE_PROJECT_ID }}'
                  env: true
                  group: e2e tests
                  headless: true
                  parallel: true
                  record: true
                  spec: cypress/integration/*

    install_dependencies:
        name: Install dependencies
        runs-on: ubuntu-latest
        env:
            NEXT_TELEMETRY_DISABLED: 1
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: yarn install
            - uses: actions/cache@v1
              id: cache-build
              with:
                  path: .
                  key: '${{ github.sha }}'

    test_unit:
        name: Run unit tests
        runs-on: ubuntu-latest
        needs: install_dependencies
        env:
            CI: true
        steps:
            - uses: actions/cache@v1
              id: restore-build
              with:
                  path: .
                  key: '${{ github.sha }}'
            - name: Unit tests
              run: yarn test
